stages:
  - test
  - allure

Test:
  stage: test
  tags:
    - runner-free
  image: maven:latest
  script:
    - mvn test
  after_script:
    - ls -al

Allure:
  stage: allure
  script:
    - allure generate api_target_allure-results -o allure-report
  artifacts:
    paths:
      - allure-report